# Stop-hook freshness gate, mirroring the cheap pre-commit gates. Exits 0 silently when
# nothing relevant is dirty; exits 2 (blocks the stop, feeds stderr back to Claude) only
# when a bake / contract copy / head-include is actually stale. Not the full preflight
# (tests/import/smoke/export) — that is minutes long.
$ErrorActionPreference = 'Continue'
$repo  = Split-Path -Parent $PSScriptRoot
Set-Location $repo
. (Join-Path $PSScriptRoot 'godot_bin.ps1')

# Loop guard: if Claude was already re-woken once by this hook, don't block again.
$raw = try { [Console]::In.ReadToEnd() } catch { '' }
try { $stdin = $raw | ConvertFrom-Json } catch { $stdin = $null }

# Allowing the stop: hand off to the user's optional notifier (it skips Stop events here,
# because hooks run in parallel and only this one knows whether Claude really stopped).
function Allow {
    $notify = Join-Path $env:USERPROFILE '.claude\claude-notify.ps1'
    if (Test-Path $notify) { $env:CLAUDE_NOTIFY_FROM_GATE = '1'; $raw | & $notify }
    exit 0
}
if ($stdin -and $stdin.stop_hook_active) { Allow }

# Cheap gate: only proceed if working-tree/staged files touch authoring surfaces.
$dirty = (git status --porcelain 2>$null) -split "`n" |
    ForEach-Object { ($_ -replace '^..\s+', '').Trim() } | Where-Object { $_ }
if (-not $dirty) { Allow }

$touchContract = $dirty | Where-Object { $_ -eq 'contract/carlito_contract.json' }
$touchHead     = $dirty | Where-Object { $_ -match '^(src/bridge/web/head_include\.html|export_presets\.cfg)$' }
# Bake-input prefixes: one list, shared with pre-commit gate 4.
$bakePaths     = Get-Content (Join-Path $PSScriptRoot 'git-hooks\bake_paths.txt') |
    Where-Object { $_ -and -not $_.StartsWith('#') }
$touchBake     = $dirty | Where-Object {
    $p = $_; -not $p.EndsWith('.md') -and ($bakePaths | Where-Object { $p.StartsWith($_) }) }

function Block($msg) { [Console]::Error.WriteLine($msg); exit 2 }
if (-not $bakePaths) { Block 'tools/git-hooks/bake_paths.txt is missing or empty, so no bake input can trigger the stale-bake check.' }

# 1. Contract edited -> synced sloppyCAN copy must be regenerated.
if ($touchContract) {
    $out = Join-Path $repo '..\sloppycan\carlito_contract.js'
    if (Test-Path $out) {
        $before = (Get-FileHash $out).Hash
        node tools/gen_js_contract.mjs | Out-Null
        if ((Get-FileHash $out).Hash -ne $before) {
            Block 'Stale sloppyCAN contract copy — it was just regenerated by the Stop hook. Review + commit it in the sloppycan repo.'
        }
    }
}

# 2. Head include touched -> pasted preset copy must match the reviewable source.
if ($touchHead) {
    node tools/check_head_include.mjs | Out-Null
    if ($LASTEXITCODE -ne 0) {
        Block 'Head-include drift (export_presets.cfg vs src/bridge/web/head_include.html) — re-paste the source into the preset.'
    }
}

# 3. Level/kit files touched -> stale-bake check (boots Godot; same gate CI runs).
# Godot is resolved only here, so a machine without GODOT_BIN set still gets gates 1-2.
if ($touchBake) {
    $GODOT = Resolve-GodotBin
    # Read the completion sentinel, not $LASTEXITCODE: headless Godot intermittently segfaults during teardown after a clean run.
    $out = (& $GODOT --headless --path . res://tools/check_bakes.tscn 2>&1) | Out-String
    # `unbuilt` (manifest verifies, no local .baked.scn) is not a failure; only stale blocks.
    $done = [regex]::Match($out, '\[check-bakes\] complete: \d+ fresh, \d+ unbuilt, (\d+) stale')
    if (-not $done.Success) {
        Block "check_bakes did not finish, so bake freshness is unknown. Re-run it:  & `$GODOT --headless --path . res://tools/check_bakes.tscn`n$out"
    }
    if ([int]$done.Groups[1].Value -ne 0) {
        # Unanchored: PowerShell 5.1 prefixes the first captured stderr line with the exe name.
        $why = ($out -split "`n" | Where-Object { $_ -match '\[check-bakes\] .*: (stale|missing|error)' }) -join "`n"
        Block "Stale bakes or road paint (fix as named), then re-bake:  & `$GODOT --headless --path . res://tools/bake_levels.tscn`n$why"
    }
}

Allow
